# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Test
      run: dotnet test --verbosity normal

    - name: dotnet publish
      run: dotnet publish ChatWithMAI/ChatWithMAI.csproj --configuration Release -o artifacts

    - uses: actions/upload-artifact@v4
      with:
        name: ChatWithMAIPublished
        path: artifacts/
  
  deploy_dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ChatWithMAIPublished
          path: azure_artifacts/
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: app-chatwithmai-dev
          package: azure_artifacts/
