# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Test
      run: dotnet test --verbosity normal

    - name: dotnet publish
      run: dotnet publish ChatWithMAI/ChatWithMAI.csproj --configuration Release -o artifacts

    - uses: actions/upload-artifact@v4
      with:
        name: ChatWithMAIPublished
        path: artifacts/
